/* =================== API请求配置 ================ */
export const BASE_API = process.env.NODE_ENV === 'production' ? process.env.VUE_APP_BASE_API : '';
export const API_SERVICE = `${BASE_API}`;
export const ISC__SERVICE = `${BASE_API}/ocloud/auth/oauth`;
export const CONFIG_SERVICE = `${BASE_API}/cnpdg`;
export const SYS_PATH = `${BASE_API}/system-server`;
export const AUTH_PATH = `${BASE_API}/auth-server`;
export const DEVTOOLS_PATH = `${BASE_API}/devtools-server`;
export const FLOW_PATH = `${BASE_API}/flowable-server`;
export const ELASTICSEARCH_PATH = `${BASE_API}/elasticsearch-server/elasticsearch`;
export const FILE_PATH = `${BASE_API}/file-server`;
export const UREPORT_PATH = `${BASE_API}/ureport-server`;
export const WPS_PATH = `${BASE_API}/wps-server`;
export const TEST_PATH = `${BASE_API}/test-server`;

/* =================== localStorage key ================ */
export const TOKEN = 'token';
export const REFRESH_TOKEN = 'refresh_token';
export const AUTO_LOGIN = 'auto_login';
export const USER_INFO = 'USER_INFO';
export const MENU_LIST = 'MENU';
export const ROLE_LIST = 'ROLE_LIST';
export const ROLE_LIST_INDEX = 'ROLE_LIST_INDEX';
export const PERMISSIONS_LIST = 'PERMISSIONS';
export const DICT_LIST = 'DICT_LIST';

/* =================== 模拟用户数据 ================ */
// 用户信息
export const UserInfo = {
  userId: 'zhul70',
  userName: 'zhul70',
  orgName: '测试组',
  realName: '朱亮',
};
// 菜单信息列表
export const MenuList = [
  {
    url: '/home',
    name: '首页',
    customIcon: '/home.png',
  },
  {
    name: '动态表单',
    url: '/form',
    customIcon: '/home.png',
    children: [
      {
        url: '/form/MakeFormList',
        name: '表单设计器',
      },
    ],
  },
  {
    name: '流程应用',
    url: '/flowable',
    customIcon: '/home.png',
    children: [
      {
        url: '/flowable/task',
        name: '我的事务',
        children: [
          {
            url: '/flowable/task/TodoList',
            name: '待办任务',
          },
          {
            url: '/flowable/task/HistoryList',
            name: '已办事项',
          },
          {
            url: '/flowable/task/ProcessList',
            name: '发起流程',
          },
          {
            url: '/flowable/task/ApplyList',
            name: '我发起的',
          },
          {
            url: '/flowable/extension/FlowCopyList',
            name: '抄送事项',
          },
        ],
      },
      {
        url: '/flowable/extension',
        name: '流程管理',
        children: [
          {
            url: '/flowable/process/ModelList',
            name: '流程设计',
          },
          {
            url: '/flowable/extension/ConditionList',
            name: '流程表达式',
          },
          {
            url: '/flowable/extension/ButtonList',
            name: '常用按钮',
          },
          {
            url: '/flowable/extension/ActCategoryList',
            name: '分类管理',
          },
          {
            url: '/flowable/extension/ListenerList',
            name: '流程监听器',
          },
        ],
      },
      {
        url: '/flowable/process',
        name: '流程监控',
        children: [
          {
            url: '/flowable/process/RunningList',
            name: '未完成',
          },
          {
            url: '/flowable/process/HistoryList',
            name: '已完成',
          },
        ],
      },
      {
        url: '/flowable/form/FormDefinitionList',
        name: '流程表单',
      },
    ],
  },
  {
    name: '数据管理',
    url: '/database',
    customIcon: '/home.png',
    children: [
      {
        url: '/database/datalink/DataSourceList',
        name: '数据源管理',
      },
      {
        url: '/database/datamodel/DataSetList',
        name: '数据集管理',
      },
      {
        url: '/database/datatable/Table',
        name: '数据库表管理',
      },
    ],
  },
  {
    name: '系统管理',
    url: '/sys',
    customIcon: '/home.png',
    children: [
      {
        url: '/sys/dict',
        name: '区域管理',
        children: [
          {
            url: '/sys/dict/DictTypeList',
            name: '字典管理',
          },
        ],
      },
      {
        url: '/sys/question',
        name: '问答列表',
      },
    ],
  },
];
// 角色信息列表
export const RoleList = [
  {
    userId: 'zhul70',
    id: '8a65eac66d632e14016d6707c9de02d1',
    code: 'IN_SYS_ADMIN',
    name: '系统管理员',
  },
  {
    userId: 'hbtydlgcyxgs',
    id: '8a65eac66d632e14016d6709614702d6',
    code: 'OUT_SGDW',
    name: '施工单位',
  },
  {
    userId: 'hnxjdlfwyxgs',
    id: '8a65eac66d632e14016d67099ac602d7',
    code: 'OUT_JLDW',
    name: '监理单位',
  },
];
// 权限列表
export const PermissionsList = [
  'ny:nyRuleHistory:list',
  'test:onetomany:testDataMain:export',
  'gencode:validateType:view',
  'ureport:add',
  'extension:actCategory:del',
  'test:manytomany:testCourse:list',
  'test:grid:testCountry:del',
  'test:validation:testValidation:add',
  'sys:office:del',
  'database:datalink:dataSource:view',
  'gencode:table:del',
  'test:manytomany:testStudentCourse:list',
  'gencode:validateType:list',
  'gencode:codeParam:add',
  'test:onetomany:testDataMain:list',
  'extension:button:add',
  'echarts:del',
  'extension:formDefinition:edit',
  'test:manytomany:testStudent:import',
  'test:manytomany:testStudent:view',
  'test:pic:testPic:export',
  'extension:formDefinition:del',
  'form:jp_form_1631264005780:import',
  'sys:post:import',
  'ny:nyRuleHistory:del',
  'sys:menu:del',
  'form:jp_form_1631264005780:edit',
  'extension:button:import',
  'sys:role:datarule',
  'test:grid:testContinent:edit',
  'gencode:showType:add',
  'test:manytomany:testStudent:list',
  'sys:area:view',
  'test:grid:testCountry:list',
  'notify:view',
  'sys:file:add',
  'test:shop:testGoods:del',
  'sys:sysConfig:import',
  'database:datalink:dataSource:list',
  'datav:dataScreenCategory:del',
  'test:grid:testCountry:view',
  'test:manytomany:testStudentCourse:view',
  'test:shop:testCategory:export',
  'datav:dataMap:del',
  'gencode:tableColumn:edit',
  'gencode:customObj:import',
  'test:manytomany:testCourse:view',
  'notify:list',
  'form:make:add',
  'ny:nyRuleHistory:view',
  'gencode:validateType:import',
  'extension:flowCopy:add',
  'extension:formDefinition:import',
  'sys:post:list',
  'test:shop:testCategory:import',
  'test:validation:testValidation:export',
  'wps:docTemplate:add',
  'sys:area:add',
  'extension:flowCopy:edit',
  'test:treetable:testCar:import',
  'datav:dataMap:import',
  'echarts:dashboard:list',
  'sys:post:del',
  'sys:log:view',
  'test:grid:testContinent:add',
  'extension:condition:view',
  'test:note:testNote:del',
  'test:tree:testTree:list',
  'test:one:testFormLeave:view',
  'test:tree:testTree:view',
  'extension:listener:edit',
  'extension:condition:list',
  'test:one:testFormLeave:list',
  'database:datalink:dataSource:del',
  'test:manytomany:testStudentCourse:export',
  'datav:dataScreen:view',
  'sys:role:assign',
  'test:pic:testPic:del',
  'echarts:dashboard:view',
  'test:pic:testPic:import',
  'sys:post:view',
  'test:grid:testContinent:export',
  'sys:role:del',
  'extension:condition:import',
  'sys:sysConfig:del',
  'test:onetomany:testDataMain:view',
  'datav:dataScreen:list',
  'extension:condition:export',
  'extension:condition:del',
  'gencode:codeParam:view',
  'gencode:dataBaseType:export',
  'test:treetable:testCar:del',
  'notify:add',
  'test:pic:testPic:view',
  'extension:flowCopy:export',
  'gencode:queryType:del',
  'sys:file:edit',
  'echarts:dashboard:add',
  'gencode:codeParam:list',
  'gencode:dataBaseType:add',
  'gencode:customObj:edit',
  'sys:log:list',
  'test:pic:testPic:list',
  'test:grid:testContinent:view',
  'test:manytomany:testCourse:import',
  'test:grid:testContinent:list',
  'gencode:table:add',
  'test:manytomany:testCourse:del',
  'gencode:validateType:del',
  'database:datamodel:dataSet:add',
  'database:datamodel:dataSet:view',
  'ny:nyRuleHistory:add',
  'gencode:queryType:add',
  'datav:dataScreen:add',
  'ny:nyRuleHistory:edit',
  'test:treetable:testCar:export',
  'extension:actCategory:add',
  'extension:listener:del',
  'gencode:customObj:export',
  'sys:office:edit',
  'test:shop:testCategory:edit',
  'sys:role:auth',
  'test:one:testFormLeave:import',
  'extension:condition:add',
  'echarts:dashboard:import',
  'sys:file:del',
  'echarts:list',
  'extension:flowCopy:import',
  'sys:user:del',
  'sys:post:add',
  'test:note:testNote:edit',
  'database:datalink:dataSource:edit',
  'test:treetable:testCar:view',
  'sys:language:del',
  'gencode:showType:export',
  'test:manytomany:testStudentCourse:add',
  'extension:flowCopy:del',
  'test:treetable:testCar:list',
  'sys:log:del',
  'echarts:view',
  'sys:post:edit',
  'sys:user:edit',
  'gencode:showType:del',
  'sys:tenant:edit',
  'test:manytomany:testStudentCourse:import',
  'gencode:queryType:import',
  'sys:office:add',
  'gen:customObj:del',
  'extension:formDefinition:add',
  'test:tree:testTree:edit',
  'datav:dataScreenCategory:edit',
  'test:onetomany:testDataMain:import',
  'echarts:dashboard:export',
  'form:make:view',
  'sys:sysConfig:view',
  'gencode:customObj:list',
  'gencode:customObj:del',
  'extension:flowCopy:list',
  'test:validation:testValidation:view',
  'extension:actCategory:edit',
  'form:make:list',
  'sys:dict:view',
  'test:shop:testGoods:edit',
  'extension:button:edit',
  'datav:dataMap:edit',
  'test:validation:testValidation:list',
  'form:jp_form_1631264005780:add',
  'gencode:customObj:view',
  'sys:dict:list',
  'sys:role:add',
  'notify:del',
  'sys:post:export',
  'test:manytomany:testStudentCourse:edit',
  'ureport:view',
  'gencode:table:list',
  'form:jp_form_1631264005780:export',
  'test:one:testFormLeave:export',
  'sys:language:list',
  'gencode:dataBaseType:del',
  'test:treetable:testCar:add',
  'gencode:table:view',
  'test:manytomany:testStudent:export',
  'test:pic:testPic:add',
  'test:one:testFormLeave:del',
  'extension:listener:import',
  'test:shop:testGoods:export',
  'extension:listener:list',
  'gencode:dataBaseType:edit',
  'sys:language:view',
  'wps:docTemplate:edit',
  'database:datalink:dataSource:add',
  'extension:listener:view',
  'sys:menu:edit',
  'database:datamodel:dataSet:list',
  'test:onetomany:testDataMain:add',
  'extension:listener:add',
  'flowable:model:list',
  'echarts:edit',
  'sys:user:add',
  'gencode:queryType:edit',
  'sys:role:edit',
  'test:shop:testGoods:import',
  'test:treetable:testCar:edit',
  'extension:listener:export',
  'gencode:codeParam:export',
  'sys:office:view',
  'test:tree:testTree:export',
  'wps:docTemplate:del',
  'gencode:validateType:add',
  'test:shop:testCategory:del',
  'test:manytomany:testStudent:add',
  'test:manytomany:testCourse:add',
  'test:note:testNote:view',
  'database:datalink:dataSource:import',
  'test:note:testNote:list',
  'extension:flowCopy:view',
  'sys:menu:updateSort',
  'sys:tenant:add',
  'sys:office:list',
  'test:one:testFormLeave:edit',
  'test:note:testNote:export',
  'gencode:queryType:export',
  'form:make:del',
  'sys:dict:edit',
  'datav:dataMap:view',
  'test:grid:testCountry:edit',
  'extension:actCategory:import',
  'sys:menu:add',
  'datav:dataMap:add',
  'sys:menu:list',
  'sys:area:edit',
  'test:validation:testValidation:edit',
  'test:note:testNote:import',
  'test:manytomany:testCourse:export',
  'form:jp_form_1631264005780:del',
  'datav:dataMap:list',
  'test:tree:testTree:add',
  'datav:dataScreenCategory:list',
  'gencode:table:edit',
  'sys:sysConfig:edit',
  'datav:dataScreenCategory:view',
  'echarts:dashboard:deploy',
  'form:make:edit',
  'test:tree:testTree:import',
  'sys:tenant:list',
  'sys:menu:view',
  'sys:dict:del',
  'database:datamodel:dataSet:edit',
  'test:manytomany:testCourse:edit',
  'gencode:customObj:add',
  'database:datalink:dataSource:export',
  'ny:nyRuleHistory:import',
  'gencode:table:importDb',
  'extension:button:list',
  'test:validation:testValidation:del',
  'datav:dataMap:export',
  'gencode:showType:edit',
  'extension:button:view',
  'form:make:deploy',
  'test:validation:testValidation:import',
  'gencode:showType:import',
  'wps:docTemplate:list',
  'sys:file:export',
  'test:shop:testCategory:add',
  'wps:docTemplate:view',
  'test:shop:testGoods:add',
  'echarts:add',
  'extension:formDefinition:export',
  'extension:button:del',
  'notify:edit',
  'sys:user:export',
  'gencode:tableColumn:view',
  'form:jp_form_1631264005780:view',
  'sys:role:view',
  'extension:actCategory:export',
  'datav:dataScreenCategory:add',
  'sys:language:edit',
  'test:grid:testCountry:export',
  'gencode:validateType:export',
  'test:one:testFormLeave:add',
  'test:onetomany:testDataMain:del',
  'test:manytomany:testStudent:edit',
  'sys:role:list',
  'gencode:dataBaseType:list',
  'test:grid:testCountry:add',
  'extension:button:export',
  'sys:area:del',
  'extension:actCategory:view',
  'ny:nyRuleHistory:export',
  'test:manytomany:testStudent:del',
  'gencode:dataBaseType:import',
  'test:shop:testGoods:view',
  'extension:actCategory:list',
  'gencode:dataBaseType:view',
  'sys:tenant:del',
  'test:onetomany:testDataMain:edit',
  'test:grid:testContinent:import',
  'gencode:table:synchDb',
  'echarts:dashboard:edit',
  'test:grid:testCountry:import',
  'test:shop:testGoods:list',
  'gencode:validateType:edit',
  'echarts:dashboard:design',
  'gencode:showType:view',
  'gencode:showType:list',
  'sys:file:view',
  'test:manytomany:testStudentCourse:del',
  'sys:file:import',
  'extension:condition:edit',
  'sys:user:import',
  'test:grid:testContinent:del',
  'extension:formDefinition:list',
  'sys:area:list',
  'sys:sysConfig:export',
  'extension:formDefinition:view',
  'sys:dict:add',
  'sys:language:add',
  'sys:file:list',
  'sys:sysConfig:add',
  'sys:sysConfig:index',
  'sys:user:view',
  'test:pic:testPic:edit',
  'database:datamodel:dataSet:del',
  'sys:user:list',
  'gencode:codeParam:del',
  'gencode:queryType:view',
  'test:shop:testCategory:view',
  'echarts:dashboard:del',
  'gencode:codeParam:edit',
  'gencode:queryType:list',
  'test:note:testNote:add',
  'test:tree:testTree:del',
  'gencode:table:genCode',
  'gencode:codeParam:import',
  'datav:dataScreen:del',
  'datav:dataScreen:edit',
  'test:shop:testCategory:list',
];
