export const basicComponents = [
  {
    type: 'input',
    icon: 'icon-input',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      width: '',
      defaultValue: '',
      required: false,
      requiredMessage: '',
      dataType: '',
      dataTypeCheck: false,
      dataTypeMessage: '',
      pattern: '',
      patternCheck: false,
      patternMessage: '',
      validatorCheck: false,
      validator: '',
      placeholder: '',
      customClass: '',
      disabled: false,
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      showPassword: false,
      clearable: false,
      // jeeplus begin
      isShow: true,
      isSort: true,
      isSearch: true,
    },
    events: {
      onChange: '',
      onFocus: '',
      onBlur: '',
    },
  },
  {
    type: 'textarea',
    icon: 'icon-diy-com-textarea',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      width: '',
      defaultValue: '',
      required: false,
      requiredMessage: '',
      disabled: false,
      pattern: '',
      patternMessage: '',
      validatorCheck: false,
      validator: '',
      placeholder: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      clearable: false,
      // jeeplus begin
      isShow: true,
      isSort: true,
      isSearch: false,
    },
    events: {
      onChange: '',
      onFocus: '',
      onBlur: '',
    },
  },
  {
    type: 'number',
    icon: 'icon-number',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      width: '',
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      defaultValue: 0,
      min: 0,
      max: 9,
      step: 1,
      disabled: false,
      controls: true,
      controlsPosition: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      precision: 0,
      // jeeplus begin
      isShow: true,
      isSort: true,
      isSearch: false,
    },
    events: {
      onChange: '',
      onFocus: '',
      onBlur: '',
    },
  },
  {
    type: 'radio',
    icon: 'icon-radio-active',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      inline: false,
      defaultValue: '',
      showLabel: false,
      options: [
        {
          value: 'Option 1',
          label: 'Option 1',
        },
        {
          value: 'Option 2',
          label: 'Option 2',
        },
        {
          value: 'Option 3',
          label: 'Option 3',
        },
      ],
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      width: '',
      remote: 1,
      remoteType: 'datasource',
      remoteOption: '',
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      disabled: false,
      // jeeplus begin
      isShow: true,
      isSort: true,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'checkbox',
    icon: 'icon-check-box',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      inline: false,
      defaultValue: [],
      showLabel: false,
      options: [
        {
          value: 'Option 1',
        },
        {
          value: 'Option 2',
        },
        {
          value: 'Option 3',
        },
      ],
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      width: '',
      remote: 1,
      remoteType: 'datasource',
      remoteOption: '',
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      disabled: false,
      // jeeplus begin
      isShow: true,
      isSort: true,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'select',
    icon: 'icon-select',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: '',
      multiple: false,
      disabled: false,
      clearable: false,
      placeholder: '',
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      showLabel: false,
      width: '',
      options: [
        {
          value: 'Option 1',
        },
        {
          value: 'Option 2',
        },
        {
          value: 'Option 3',
        },
      ],
      remote: 1,
      remoteType: 'datasource',
      remoteOption: '',
      filterable: false,
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
      onFocus: '',
      onBlur: '',
    },
  },
  {
    type: 'time',
    icon: 'icon-time',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: '',
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      placeholder: '',
      startPlaceholder: '',
      endPlaceholder: '',
      isRange: false,
      arrowControl: false,
      format: 'HH:mm:ss',
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      width: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
      onFocus: '',
      onBlur: '',
    },
  },
  {
    type: 'date',
    icon: 'icon-date',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: '',
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      placeholder: '',
      startPlaceholder: '',
      endPlaceholder: '',
      type: 'date',
      format: 'YYYY-MM-DD',
      timestamp: false,
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      width: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
      onFocus: '',
      onBlur: '',
    },
  },
  {
    type: 'rate',
    icon: 'icon-pingfen1',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: null,
      max: 5,
      disabled: false,
      allowHalf: false,
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      showScore: false,
      // jeeplus begin
      isShow: true,
      isSort: true,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'color',
    icon: 'icon-color',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: '',
      disabled: false,
      showAlpha: false,
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'switch',
    icon: 'icon-switch',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: false,
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      disabled: false,
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      width: '',
      // jeeplus begin
      isShow: true,
      isSort: true,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'slider',
    icon: 'icon-slider',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: 0,
      disabled: false,
      required: false,
      requiredMessage: '',
      validatorCheck: false,
      validator: '',
      min: 0,
      max: 100,
      step: 1,
      showInput: false,
      range: false,
      width: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'text',
    icon: 'icon-wenzishezhi-',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: 'This is a text',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      required: false,
      // jeeplus begin
      isShow: true,
      isSort: true,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'html',
    icon: 'icon-html',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: '<b style="color: red;">\n\tThis is a HTML5\n</b>',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      required: false,
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'button',
    icon: 'icon-button',
    options: {
      customClass: '',
      disabled: false,
      labelWidth: 100,
      isLabelWidth: false,
      hideLabel: true,
      hidden: false,
      dataBind: false,
      buttonSize: 'default',
      buttonType: '',
      buttonPlain: false,
      buttonRound: false,
      buttonCircle: false,
      buttonName: 'Button',
      width: '',
    },
    events: {
      onClick: '',
    },
  },
  {
    type: 'link',
    icon: 'icon-lianjie',
    options: {
      customClass: '',
      disabled: false,
      labelWidth: 100,
      isLabelWidth: false,
      hideLabel: false,
      hidden: false,
      dataBind: false,
      linkType: 'default',
      linkName: 'Link',
      underline: true,
      blank: true,
      href: '',
    },
    events: {
      onClick: '',
    },
  },
  {
    type: 'cascader',
    icon: 'icon-jilianxuanze',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: [],
      width: '',
      placeholder: '',
      disabled: false,
      clearable: false,
      options: [
        {
          value: 'Option 1',
          label: 'Option 1',
          children: [
            { value: 'Option 1 - children', label: 'Option 1 - children' },
          ],
        },
        {
          value: 'Option 2',
          label: 'Option 2',
          children: [
            { value: 'Option 2 - children', label: 'Option 2 - children' },
          ],
        },
        {
          value: 'Option 3',
          label: 'Option 3',
        },
      ],
      remote: false,
      remoteType: 'datasource',
      remoteOption: '',
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
        children: 'children',
      },
      remoteFunc: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      required: false,
      validatorCheck: false,
      validator: '',
      multiple: false,
      filterable: false,
      checkStrictly: false, // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
      onFocus: '',
      onBlur: '',
    },
  },
  {
    type: 'treeselect',
    icon: 'icon-shuxuanzeqi',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: [],
      width: '',
      placeholder: '',
      disabled: false,
      clearable: false,
      options: [
        {
          value: 'Option 1',
          label: 'Option 1',
          children: [
            { value: 'Option 1 - children', label: 'Option 1 - children' },
          ],
        },
        {
          value: 'Option 2',
          label: 'Option 2',
          children: [
            { value: 'Option 2 - children', label: 'Option 2 - children' },
          ],
        },
        {
          value: 'Option 3',
          label: 'Option 3',
        },
      ],
      remote: false,
      remoteType: 'datasource',
      remoteOption: '',
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
        children: 'children',
      },
      remoteFunc: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      required: false,
      validatorCheck: false,
      validator: '',
      multiple: false,
      filterable: false,
      checkStrictly: false,
      // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
      onFocus: '',
      onBlur: '',
    },
  },
  {
    type: 'steps',
    icon: 'icon-m-buzhou',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: 0,
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hideLabel: true,
      hidden: false,
      dataBind: true,
      steps: [
        {
          title: 'Step 1',
        },
        {
          title: 'Step 2',
        },
        {
          title: 'Step 3',
        },
      ],
      props: {
        title: 'title',
        description: 'description',
      },
      remote: false,
      width: '',
      direction: 'horizontal',
      processStatus: 'process',
      finishStatus: 'finish',
      alignCenter: false,
      simple: false, // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'transfer',
    icon: 'icon-m-chuansuokuang',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: [],
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hideLabel: false,
      hidden: false,
      dataBind: true,
      data: [
        { key: '1', label: 'Option 1' },
        { key: '2', label: 'Option 2' },
        { key: '3', label: 'Option 3' },
      ],
      props: {
        key: 'key',
        label: 'label',
        disabled: 'disabled',
      },
      filterable: false,
      required: false,
      validatorCheck: false,
      validator: '',
      width: '',
      remote: false,
      titles: ['Source', 'Target'],
      disabled: false, // jeeplus begin
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
]

export const advanceComponents = [
  {
    type: 'blank',
    icon: 'icon-zidingyishuju',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultType: 'String',
      customClass: '',
      width: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      required: false,
      pattern: '',
      validator: '',
      //jeeplus
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'component',
    icon: 'icon-component',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      template: '<div>自定义内容</div>',
      required: false,
      pattern: '',
      validator: '',
      //jeeplus
      isShow: true,
      isSort: false,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'fileupload',
    icon: 'icon-wenjianshangchuan',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: [],
      width: '',
      tokenFunc: 'funcGetToken',
      token: '',
      tokenType: 'datasource',
      domain: '', //jeeplus
      disabled: false,
      tip: '',
      action: '', //jeeplus
      customClass: '',
      limit: 9,
      multiple: false,
      isQiniu: false,
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      headers: [],
      required: false,
      validatorCheck: false,
      validator: '',
      withCredentials: false,
      //jeeplus
      isShow: true,
      isSort: false,
    },
    events: {
      onChange: '',
      onSelect: '',
      onUploadSuccess: '',
      onUploadError: '',
      onRemove: '',
    },
  },
  {
    type: 'imgupload',
    icon: 'icon-tupian',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: [],
      size: {
        width: 100,
        height: 100,
      },
      width: '',
      tokenFunc: 'funcGetToken',
      token: '',
      tokenType: 'datasource',
      domain: '', //jeeplus
      disabled: false,
      readonly: false,
      limit: 8,
      multiple: false,
      isQiniu: false,
      isDelete: true,
      min: 0,
      isEdit: true,
      action: '', //jeeplus
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      headers: [],
      required: false,
      validatorCheck: false,
      validator: '',
      withCredentials: false,
      isShow: true,
      isSort: false,
    },
    events: {
      onChange: '',
      onSelect: '',
      onUploadSuccess: '',
      onUploadError: '',
      onRemove: '',
    },
  },
  {
    type: 'editor',
    icon: 'icon-fuwenbenkuang',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: '',
      width: '',
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      customToolbar: [
        [
          'bold',
          'italic',
          'underline',
          'strike',
          { color: [] },
          { background: [] },
          { align: [] },
          { list: 'ordered' },
          { list: 'bullet' },
          { indent: '-1' },
          { indent: '+1' },
        ],
        [{ font: [] }, { header: [1, 2, 3, 4, 5, 6, false] }],
        [{ script: 'sub' }, { script: 'super' }],
        ['link', 'image', 'blockquote', 'code-block'],
        [{ direction: 'rtl' }],
        ['clean'],
      ],
      disabled: false,
      required: false,
      validatorCheck: false,
      validator: '',
      required: false,
      isShow: true,
      isSort: true,
      isSearch: false,
    },
    events: {
      onChange: '',
    },
  },
  {
    type: 'table',
    icon: 'icon-table',
    //jeeplus 定制
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    //jeeplus end
    options: {
      defaultValue: [],
      customClass: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      disabled: false,
      required: false,
      validatorCheck: false,
      validator: '',
      paging: false,
      pageSize: 5,
      isShow: false, // jeeplus
    },
    events: {
      onChange: '',
      onRowAdd: '',
      onRowRemove: '',
      onRowChange: '',
    },
    tableColumns: [],
  },
  {
    type: 'user',
    icon: 'icon-yonghu',
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    options: {
      defaultType: 'String',
      customClass: '',
      defaultValue: '',
      width: '',
      limit: 1,
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      required: false,
      disabled: false,
      clearable: false,
      isShow: true,
      isSort: true,
      isSearch: false,
    },
  },
  {
    type: 'office',
    icon: 'icon-bumenguanli',
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    options: {
      defaultType: 'String',
      customClass: '',
      defaultValue: '',
      width: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      required: false,
      clearable: false,
      disabled: false,
      isShow: true,
      isSort: true,
      isSearch: false,
    },
  },
  {
    type: 'area',
    icon: 'icon-quyu',
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    options: {
      defaultType: 'String',
      customClass: '',
      width: '',
      labelWidth: 100,
      isLabelWidth: false,
      hidden: false,
      dataBind: true,
      required: false,
      disabled: false,
      clearable: false,
      isShow: true,
      isSort: true,
      isSearch: false,
    },
  },
  {
    type: 'dict',
    icon: 'icon-shujuzidian',
    dsId: '',
    tableName: '',
    primaryKey: '',
    foreignKey: '',
    options: {
      defaultType: 'String',
      customClass: '',
      width: '',
      labelWidth: 100,
      isLabelWidth: false,
      dictType: '',
      hidden: false,
      dataBind: true,
      required: false,
      disabled: false,
      clearable: false,
      isShow: true,
      isSort: true,
      isSearch: false,
    },
  },
]

export const layoutComponents = [
  {
    type: 'grid',
    icon: 'icon-RectangleCopy',
    columns: [
      {
        type: 'col',
        options: {
          span: 12,
          offset: 0,
          push: 0,
          pull: 0,
          xs: 24,
          sm: 12,
          md: 12,
          lg: 12,
          xl: 12,
          customClass: '',
        },
        list: [],
      },
    ],
    options: {
      gutter: 0,
      justify: 'start',
      align: 'top',
      customClass: '',
      hidden: false,
      flex: true,
      responsive: true,
    },
  },
  {
    type: 'report',
    icon: 'icon-table1',
    options: {
      customClass: '',
      hidden: false,
      borderWidth: 1,
      borderColor: '#999',
      width: '100%',
    },
    rows: [
      {
        columns: [
          {
            type: 'td',
            options: {
              customClass: '',
              colspan: 1,
              rowspan: 1,
              align: 'left',
              valign: 'top',
              width: '',
              height: '',
            },
            list: [],
          },
        ],
      },
    ],
  },
  {
    type: 'tabs',
    icon: 'icon-tabs',
    tabs: [
      {
        label: 'Tab 1',
        name: 'tab_1',
        list: [],
      },
    ],
    options: {
      type: '',
      tabPosition: 'top',
      customClass: '',
      hidden: false,
    },
  },
  {
    type: 'inline',
    icon: 'icon-inlineview',
    options: {
      customClass: '',
      hidden: false,
      spaceSize: 10,
    },
    list: [],
  },
  {
    type: 'divider',
    icon: 'icon-fengexian',
    options: {
      hidden: false,
      contentPosition: 'left',
    },
  },
  {
    type: 'alert',
    icon: 'icon-jinggaotishi',
    options: {
      hidden: false,
      title: 'Info alert',
      type: 'info',
      description: '',
      closable: true,
      center: false,
      showIcon: false,
      effect: 'light',
      width: '',
    },
  },
]
